# Generated by Django 4.1.3 on 2022-12-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('secondName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phoneNumber', models.IntegerField()),
                ('national_ID', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('role', models.BooleanField(default=False)),
            ],
        ),
    ]
