# Generated by Django 4.1.3 on 2022-12-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookName", models.CharField(max_length=100)),
                ("bookAuthor", models.CharField(max_length=100)),
                ("bookDescription", models.TextField()),
                ("bookTotal", models.IntegerField()),
                ("bookImage", models.ImageField(upload_to="pictures")),
            ],
        ),
    ]
